api/urls.py
from django.urls import path
from .views import  api_home_page, note_detail

app_name = 'api'

urlpatterns=[
    path('notes/', api_home_page, name='api_view'),
    path('notes/<int:pk>/', note_detail, name='api_view_detail'),


]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from api.views import CreateUserView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('pages.urls')),
    path('api/user/register/', CreateUserView.as_view(), name='user-register'),
    path('user-auth/', include('rest_framework.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),   
    path('api/token/',TokenObtainPairView.as_view(), name='token'),
    path('api/token/refresh/',TokenRefreshView.as_view(), name='token-refresh'),  
] 

# if settings.DEBUG:
#     import debug_toolbar

#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns
    

pages/urls.py
from django.urls import path
from .views import  home_page_view

app_name = 'pages'

urlpatterns=[
    path('', home_page_view, name='home_page_view'),
    
]

api/models.py
from django.db import models
from django.contrib.auth.models import User

class Note(models.Model):
    content = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notes')
    
    def __str__(self) :
        return f'{self.content[0:50]} by {self.author.username}'
    

pages/models.py
from django.db import models

# Create your models here.

api/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import NoteSerializer, UserSerializer
from .models import Note
from rest_framework import status, generics
from rest_framework.permissions import AllowAny, IsAuthenticated
from django.contrib.auth.models import User


@api_view(['GET', 'POST'])
def api_home_page(request):
   try:
      note_queryset = Note.objects.filter(author=request.user)
   except:
      return Response("ERROR",status=status.HTTP_400_BAD_REQUEST)
   if request.method == 'GET':
      note_queryset = Note.objects.all()
      serializeData = NoteSerializer(note_queryset, many=True).data
      return Response(serializeData)
      
   if request.method == 'POST':
      data = request.data
      serializeData = NoteSerializer(data=data)
      if serializeData.is_valid():
         serializeData.save()
         return Response(serializeData.data, status=status.HTTP_201_CREATED)
      return Response(serializeData.errors, status=status.HTTP_400_BAD_REQUEST)
         


@api_view(['GET','PUT', 'DELETE'])
def note_detail(request, pk):
   try:
      note = Note.objects.get(id=pk)
   except Note.DoesNotExist:
      return Response(status=status.HTTP_404_NOT_FOUND)
   
   if request.method == 'GET':
      serializeData = NoteSerializer(note)
      return Response(serializeData.data, status=status.HTTP_200_OK)
   
   if request.method == 'PUT':
      data = request.data
      serializeData = NoteSerializer(note, data=data)
      if serializeData.is_valid():
         serializeData.save()
         return Response(serializeData.data, status=status.HTTP_201_CREATED)
      return Response(serializeData.errors, status=status.HTTP_400_BAD_REQUEST)

   if request.method == 'DELETE':
      note.delete()
      return Response('Successfully Delete', status=status.HTTP_204_NO_CONTENT)
   
class CreateUserView(generics.CreateAPIView):
   queryset = User.objects.all()
   serializer_class = UserSerializer
   permission_classes = [AllowAny]

pages/views.py
from django.shortcuts import render


def home_page_view(request):
    return render(request, 'home.html')

pages/templates/base.html
<html>
<head>
    {%block title %}
    <h1>This is trial of my project</h1>
    {%endblock title%}
</head>
<body>
    {%block content %}
    {%endblock content %}
</body>
</html>

pages/templates/home.html
{% extends 'base.html' %}


{%block content %}
<div style="margin: 20px;">
    <h2>Links </h2>
    <div style="margin: 20px;">
        <a style="text-decoration: none; font-size: 20px;" href="{%url 'api:api_view'%}">API - Application Programming Interface</a>
    </div>
    <div style="margin: 20px;">
        <a style="text-decoration: none; font-size: 20px;" href="{%url 'user-register'%}">User Register</a>
    </div>
    <div style="margin: 20px;">
        <a style="text-decoration: none; font-size: 20px;" href="http://localhost:8000/user-auth/login/">Login</a>
    </div>
    <div style="margin: 20px;">
        <a style="text-decoration: none; font-size: 20px;" href="{%url 'token'%}">Token</a>
    </div>
    <div style="margin: 20px;">
        <a style="text-decoration: none;font-size: 20px;" href="{%url 'token-refresh'%}">Token Refresh</a>
    </div>
    <div style="margin: 20px;">
        <a style="text-decoration: none;font-size: 20px;" href="http://localhost:8000/admin/">Admin</a>
    </div>
</div>
{%endblock content %}